# See https://github.com/troessner/reek#configuration for config options

detectors:
  IrresponsibleModule:
    exclude:
      - "Scribble" # The module defined in lib/scribble.rb

directories:
  "lib/scribble/repositories":
    ManualDispatch:
      enabled: false

  "spec":
    IrresponsibleModule:
      enabled: false
