x-app: &app
  image: scribble:latest
  mem_limit: 512m
  build:
    context: .
    dockerfile: Dockerfile.prod
    target: production
  tmpfs:
    - /tmp
  volumes:
    - .:/usr/src/app:cached
    - bundler:/usr/local/bundle:delegated
    - node_modules:/usr/src/app/node_modules:delegated
  depends_on:
    postgres:
      condition: service_healthy
  links:
    - postgres

services:
  web:
    <<: *app
    command: hanami server
    ports:
      - "${PORT:-2300}:2300"
    environment:
      PRODUCTION: 'true'
