---
# Production Docker Compose file
# https://www.heroku.com/podcasts/codeish/57-discussing-docker-containers-and-kubernetes-with-a-docker-captain - Source on that.
version: '2.4'

x-app: &app
  image: scribble:latest
  mem_limit: 512m
  build:
    context: .
    dockerfile: Dockerfile.prod
  tmpfs:
    - /tmp
  volumes:
    - .:/usr/src/app:cached
    - bundler:/usr/local/bundle:delegated
    - node_modules:/usr/src/app/node_modules:delegated
  depends_on:
    postgres:
      condition: service_healthy
  links:
    - postgres

services:
  postgres:
    image: postgres:14.3-alpine
    mem_limit: 64m
    volumes:
      - ./log:/root/log:cached
      - postgresql:/var/lib/postgresql/data:delegated
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      PSQL_HISTFILE: /root/log/.psql_history
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 2s
      retries: 10
    logging:
      driver: "json-file"

  web:
    <<: *app
    command: hanami server
    ports:
      - "${PORT:-2300}:2300"
    environment:
      PRODUCTION: 'true'

volumes:
  postgresql:
  bundler:
  node_modules:
