#!/bin/sh

function initialize_database {
  echo "---------------------"
  echo "Initializing database"
  echo "---------------------"
  bundle exec rake db:prepare
}

function migrate_database {
  echo "------------------"
  echo "Migrating database"
  echo "------------------"
  bundle exec rake db:migrate:safe
}

function start_server {
  echo "---------------"
  echo "Starting server"
  echo "---------------"
  bundle exec hanami server
}


# MAIN EXECUTION

: ${MODE:=server}
: ${INIT_DB:=false}
: ${MIGRATE_DB:=false}

echo "INIT_DB: $INIT_DB"
if $INIT_DB; then
  initialize_database
fi

echo "MIGRATE_DB: $MIGRATE_DB"
if $MIGRATE_DB; then
  migrate_database
fi

case $MODE in
  server|*)
    start_server
  ;;
esac
