# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Run Lint

env:
  RUBY_VERSION: '2.7.4' # set up a fallback before reading the .ruby-version file

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # STEP 1 - CHECKOUT REPO
      - name: Checkout Repo
        uses: actions/checkout@v3
    
      # STEP 2 - DETERMINE RUBY VERSION
      - name: Read Ruby version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ${{ github.workspace }}/.ruby-version
      - name: Save Ruby version to env var
        run: echo "${{ steps.version.outputs.content }} | cut -d'-' -f 2" >> $RUBY_VERSION

      # STEP 3 - INSTALL RUBY
      - name: Install Ruby
        uses: ruby/setup-ruby@2b019609e2b0f1ea1a2bc8ca11cb82ab46ada124
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: false
          
      # STEP 4 - INSTALL DEPENDENCIES
      - name: Install dependencies
        run: bundle install

      # STEP 5 - RUN LINTER
      - name: Run linter
        run: bundle exec rake lint
