name: Run Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # # STEP 1 - CHECKOUT REPO
      # - name: Checkout Repo
      #   uses: actions/checkout@v3

      # # STEP 2 - INSTALL RUBY
      # # will use Ruby version from the repo (either .ruby-version or Gemfile, not entirely sure)
      # - name: Install Ruby
      #   uses: ruby/setup-ruby@2b019609e2b0f1ea1a2bc8ca11cb82ab46ada124
      #   with:
      #     # setting this to "true" also runs "bundle install"
      #     bundler-cache: true

      # # STEP 3 - RUN LINTER
      # - name: Run linter
      #   run: bundle exec rake lint

      # STEP 1 - CHECKOUT REPO
      - name: Checkout Repo
        uses: actions/checkout@v3

      # STEP 2 - INSTALL DOCKER
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install ca-certificates curl gnupg lsb-release
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo chmod a+r /etc/apt/keyrings/docker.gpg
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin
          curl https://cli-assets.heroku.com/install-ubuntu.sh | sh

      # STEP 3 - BUILD IMAGE
      - name: Build Image
        run: make init

      # STEP 4 - RUN LINT
      - name: Run Lint
        run: make lint
