# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # STEP 1 - INSTALL RUBY
      - uses: actions/checkout@v3
      - name: Setup Ruby
      # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
      # change this to (see https://github.com/ruby/setup-ruby#versioning):
      # uses: ruby/setup-ruby@v1
        uses: ruby/setup-ruby@2b019609e2b0f1ea1a2bc8ca11cb82ab46ada124
        with:
          ruby-version-file: '.ruby-version'
          bundler-cache: false
          
      # STEP 2 - INSTALL DEPENDENCIES
      - name: Install dependencies
        run: bundle install

      # STEP 3 - RUN LINTER
      - name: Run linter
        run: bundle exec rake lint
