# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Run Specs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  specs:
    runs-on: ubuntu-latest

    steps:
      # STEP 1 - CHECKOUT REPO
      - name: Checkout Repo
        uses: actions/checkout@v3

      # STEP 2 - INSTALL RUBY
      # will use Ruby version from the repo (either .ruby-version or Gemfile, not entirely sure)
      - name: Install Ruby
        uses: ruby/setup-ruby@2b019609e2b0f1ea1a2bc8ca11cb82ab46ada124
        with:
          bundler-cache: true
          
      # STEP 3 - INSTALL DEPENDENCIES
      - name: Install dependencies
        run: bundle install

      # STEP 4 - RUN SPECS
      - name: Run specs
        run: bundle exec rake
